// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/Netcracker/qubership-open-telemetry-collector

go 1.22

require (
	go.opentelemetry.io/collector/confmap/provider/envprovider latest
	go.opentelemetry.io/collector/confmap/provider/fileprovider latest
	go.opentelemetry.io/collector/confmap/provider/httpprovider latest
	go.opentelemetry.io/collector/confmap/provider/httpsprovider latest
	go.opentelemetry.io/collector/confmap/provider/yamlprovider latest
	github.com/Netcracker/qubership-open-telemetry-collector/connector/sentrymetricsconnector main
	github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector latest
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension latest
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension latest
	github.com/Netcracker/qubership-open-telemetry-collector/receiver/sentryreceiver main
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver latest
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver latest
	go.opentelemetry.io/collector/receiver/otlpreceiver latest
	github.com/Netcracker/qubership-open-telemetry-collector/exporter/logtcpexporter main
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter latest
	go.opentelemetry.io/collector/exporter/debugexporter latest
	go.opentelemetry.io/collector/exporter/otlpexporter latest
	go.opentelemetry.io/collector/exporter/otlphttpexporter latest
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor latest
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor latest
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor latest
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor latest
	go.opentelemetry.io/collector/processor/batchprocessor latest
	go.opentelemetry.io/collector/otelcol v0.125.0
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)























