---

# The workflow template for automatic PR labeler.
# It requires to have a configuration file with labels and conditions to apply them.
# The configuration file should be placed in the .github folder and named auto-labeler-config.yaml.
# Example file can be found there:
# https://github.com/Netcracker/.github/blob/main/config/examples/auto-labeler-config.yaml

name: Automatic PR Labeler

on:
  pull_request:
    branches: [main]
    types:
      [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  assign-labels:
    if: (github.event.pull_request.merged == false) && (github.event.pull_request.user.login != 'dependabot[bot]') && (github.event.pull_request.user.login != 'github-actions[bot]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Execute assign labels"
        id: action-assign-labels
        uses: mauroalderete/action-assign-labels@671a4ca2da0f900464c58b8b5540a1e07133e915 # v1.5.1
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          github-token: ${{ github.token }}
          conventional-commits: "./.github/auto-labeler-config.yaml"
          maintain-labels-not-matched: true
          apply-changes: ${{ github.event.pull_request.base.repo.id == github.event.pull_request.head.repo.id }}
      - name: "Drop warning if PR from fork"
        if: ${{ github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id }}
        run: |
          {
            echo "⚠️ Pull request from fork! ⚠️";
            echo "Labels will not be applied to PR. Assign them manually please.";
            echo "Labels to assign: ${{ steps.action-assign-labels.outputs.labels-next }}";
          } >> "$GITHUB_STEP_SUMMARY"
