name: Build Artifacts

on:
  release:
    types: [created]
  push:
    branches:
    - '**'
    paths-ignore:
    - '.github/**'
    - 'docs/**'
    - 'CODE-OF-CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'README.md'
    - 'SECURITY.md'
  pull_request:
    branches:
    - '**'
    paths-ignore:
    - '.github/**'
    - 'docs/**'
    - 'CODE-OF-CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'README.md'
    - 'SECURITY.md'

permissions:
  contents: read

concurrency:
  # On main/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  multiplatform_build:
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: write
      security-events: write
    # Build PRs only if the event comes from Dependabot. Skip branch pushes
    if: github.event.pull_request.user.login != 'dependabot[bot]' || github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        component:
        - name: qubership-open-telemetry-collector
          file: Dockerfile
          context: .
        - name: qubership-open-telemetry-collector-transfer
          file: docker-transfer/Dockerfile
          context: .
    runs-on: ubuntu-latest
    name: ${{ matrix.component.name }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ matrix.component.name }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
    - name: Login to Docker Hub
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: build
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        no-cache: true
        context: ${{ matrix.component.context }}
        file: ${{ matrix.component.file }}
        platforms: linux/amd64
        # See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#fetching-metadata-about-a-pull-request
        push: ${{ github.event_name != 'pull_request' && github.actor != 'dependabot[bot]' }}
        provenance: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Analyze for critical and high CVEs
      if: ${{ steps.meta.outputs.tags != '' }}
      id: docker-scout-cves
      uses: docker/scout-action@f8c776824083494ab0d56b8105ba2ca85c86e4de # v1.18.2
      continue-on-error: true
      with:
        command: cves,recommendations
        image: ${{ steps.meta.outputs.tags }}
        sarif-file: sarif.output.json
        summary: true
        ignore-base: false
        dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
        dockerhub-password: ${{ secrets.DOCKERHUB_RW_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload SARIF result
      if: ${{ success() }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: sarif.output.json
