---
name: Link Checker

on:
  push: null
  repository_dispatch: null
  workflow_dispatch: null
permissions:
  contents: read
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@82202e5e9c2f4ef1a55a3d02563e1cb6041e5332 # v2.4.1
        with:
          args: >-
            './**/*.md'
            --verbose
            --no-progress
            --user-agent 'Mozilla/5.0 (X11; Linux x86_64) Chrome/134.0.0.0'
            --retry-wait-time 30
            --max-retries 5
            --accept 100..=103,200..=299,429
            --cookie-jar cookies.json
            --exclude-all-private
          format: markdown
          fail: true
